//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class billing
    {
        public int id { get; set; }
        public int userid { get; set; }
        public Nullable<int> prefmethod { get; set; }
        public Nullable<int> billmethod { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postcode { get; set; }
        public string country { get; set; }
        public string billemail1 { get; set; }
        public string billemail2 { get; set; }
        public string picmain { get; set; }
        public string picsec { get; set; }
        public string fax { get; set; }
    }
}
