//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class classParticipant
    {
        public int id { get; set; }
        public Nullable<int> classid { get; set; }
        public Nullable<int> ticketid { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<int> status { get; set; }
        public string surveyKey { get; set; }
        public Nullable<bool> isSurveyDone { get; set; }
        public Nullable<System.DateTime> surveyTime { get; set; }
        public Nullable<int> type { get; set; }
    }
}
