//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class classRewardsAllocation
    {
        public int id { get; set; }
        public Nullable<int> classid { get; set; }
        public Nullable<int> entityid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> rewardsPoint { get; set; }
        public string remarks { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<decimal> totalpaidprice { get; set; }
        public Nullable<int> rewardsfromprice { get; set; }
        public Nullable<int> totalrewards { get; set; }
    }
}
