//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class classDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public classDetail()
        {
            this.classDates = new HashSet<classDate>();
        }
    
        public int id { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<int> type { get; set; }
        public string code { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> promoprice { get; set; }
        public Nullable<int> seats { get; set; }
        public string classpromoitems { get; set; }
        public Nullable<bool> isGrant { get; set; }
        public Nullable<int> GrantScheme { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> HRDFScheme { get; set; }
        public string Scheme { get; set; }
        public Nullable<bool> isshowninsearch { get; set; }
        public Nullable<bool> guaranteed { get; set; }
        public Nullable<decimal> examfees { get; set; }
        public Nullable<bool> istimeticker { get; set; }
        public Nullable<System.DateTime> ttstartdate { get; set; }
        public Nullable<System.DateTime> ttenddate { get; set; }
        public Nullable<decimal> ttprice { get; set; }
        public Nullable<int> ttvenueid { get; set; }
        public Nullable<int> seatStatus { get; set; }
        public string ttvenueaddress { get; set; }
        public Nullable<bool> isexamfee { get; set; }
        public Nullable<int> rewardsType { get; set; }
        public Nullable<decimal> customerAlloc { get; set; }
        public Nullable<decimal> trainerAlloc { get; set; }
        public Nullable<decimal> quorseAlloc { get; set; }
        public Nullable<bool> isClassCompleted { get; set; }
        public Nullable<bool> isSurveySent { get; set; }
        public Nullable<System.DateTime> completeDate { get; set; }
        public string normalPriceGift { get; set; }
        public string promoPriceGift { get; set; }
        public string ttPriceGift { get; set; }
        public Nullable<bool> islunch { get; set; }
        public Nullable<bool> iscertificate { get; set; }
        public Nullable<bool> issbl { get; set; }
        public Nullable<bool> isexam { get; set; }
        public Nullable<bool> isbundle { get; set; }
        public Nullable<bool> istwelvemonths { get; set; }
        public Nullable<bool> isthirtydays { get; set; }
        public Nullable<bool> isoneeightzerodays { get; set; }
        public Nullable<bool> isusd { get; set; }
        public Nullable<bool> ninetydayaccess { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<classDate> classDates { get; set; }
        public virtual course course { get; set; }
    }
}
