//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class courseLevel1
    {
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string thumbSmall { get; set; }
        public string thumbMedium { get; set; }
        public string thumbFeatured { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
        public Nullable<int> status { get; set; }
        public string searchname { get; set; }
        public string pageTitle { get; set; }
        public string metaTitle { get; set; }
        public string metaDescription { get; set; }
        public string footerDescription { get; set; }
        public string footerTitle { get; set; }
    }
}
