//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_old
    {
        public int id { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<int> userdashid { get; set; }
        public Nullable<int> courseType { get; set; }
        public Nullable<int> coursePrincipal { get; set; }
        public Nullable<int> courseCategory { get; set; }
        public Nullable<int> courseProduct { get; set; }
        public Nullable<System.DateTime> publishDate { get; set; }
        public Nullable<System.DateTime> expirationDate { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public Nullable<bool> HRDFClaim { get; set; }
        public Nullable<int> Duration { get; set; }
        public string language { get; set; }
        public string colorHex { get; set; }
        public Nullable<decimal> courseprice { get; set; }
        public Nullable<bool> showprice { get; set; }
        public string teaser { get; set; }
        public string description { get; set; }
        public string modules { get; set; }
        public string thumbSmall { get; set; }
        public string thumbMedium { get; set; }
        public string thumbFeatured { get; set; }
        public string bgLarge { get; set; }
        public string tags { get; set; }
        public Nullable<int> CourseStatus { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public string entityguid { get; set; }
        public Nullable<int> rewardspoints { get; set; }
        public string whatyoullget { get; set; }
        public string outlineFileName { get; set; }
        public Nullable<int> availability { get; set; }
        public Nullable<decimal> overallscore { get; set; }
        public Nullable<double> courserating { get; set; }
        public Nullable<int> ratingtotal { get; set; }
        public string downloads { get; set; }
        public string recommendedAudience { get; set; }
    }
}
