//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardEnquiry
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> EntityID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> EnquiryDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> DashID { get; set; }
        public Nullable<int> TicketID { get; set; }
    }
}
