//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class enquiry
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string company { get; set; }
        public string email { get; set; }
        public int category { get; set; }
        public string description { get; set; }
        public System.DateTime creationdate { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> dashid { get; set; }
    }
}
