//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class enquiryHistory
    {
        public int id { get; set; }
        public Nullable<int> enquiryid { get; set; }
        public Nullable<int> dashid { get; set; }
        public Nullable<int> statusfrom { get; set; }
        public Nullable<int> statusto { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<int> dashidFrom { get; set; }
        public Nullable<int> dashidTo { get; set; }
    }
}
