//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class enrollenquiry
    {
        public int id { get; set; }
        public string guid { get; set; }
        public Nullable<int> dashid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> entityid { get; set; }
        public Nullable<int> bookingtype { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public string email { get; set; }
        public string fullname { get; set; }
        public string phoneno { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<int> classid { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> paxno { get; set; }
        public Nullable<decimal> totalprice { get; set; }
        public string businessrefno { get; set; }
    }
}
