//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class entity
    {
        public int id { get; set; }
        public string guid { get; set; }
        public string name { get; set; }
        public string regno { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> foundingyear { get; set; }
        public Nullable<int> noemployees { get; set; }
        public string email { get; set; }
        public string email2 { get; set; }
        public string mobilephone { get; set; }
        public string officephone { get; set; }
        public string officephone2 { get; set; }
        public string fax { get; set; }
        public string website { get; set; }
        public string addressline1 { get; set; }
        public string addressline2 { get; set; }
        public string addresscity1 { get; set; }
        public string addressstate1 { get; set; }
        public string addresspostcode1 { get; set; }
        public string country { get; set; }
        public string permission { get; set; }
        public Nullable<int> levelsapproval { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public Nullable<bool> iscreditterm { get; set; }
        public Nullable<int> creditterm { get; set; }
        public Nullable<int> parententity { get; set; }
        public string providerprincipal { get; set; }
        public string providercourses { get; set; }
        public string avatar { get; set; }
        public Nullable<int> ax1 { get; set; }
        public Nullable<int> ax2 { get; set; }
        public Nullable<int> ay1 { get; set; }
        public Nullable<int> ay2 { get; set; }
        public string profilebanner { get; set; }
        public Nullable<int> pfx1 { get; set; }
        public Nullable<int> pfx2 { get; set; }
        public Nullable<int> pfy1 { get; set; }
        public Nullable<int> pfy2 { get; set; }
        public string presentationfile { get; set; }
        public Nullable<int> tmsid { get; set; }
        public Nullable<int> rewardsPoint { get; set; }
        public Nullable<int> status { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingPostCode { get; set; }
        public string ShippingCountry { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingPostCode { get; set; }
        public string BillingCountry { get; set; }
        public Nullable<decimal> creditTermLimit { get; set; }
        public string awards { get; set; }
        public string clienteles { get; set; }
        public string testimonials { get; set; }
        public string description { get; set; }
        public string visionAndMission { get; set; }
        public Nullable<decimal> CreditTermBalance { get; set; }
    }
}
