//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam
    {
        public int id { get; set; }
        public string name { get; set; }
        public string duration { get; set; }
        public string noquestion { get; set; }
        public string exammode { get; set; }
        public string questionformat { get; set; }
        public string passingscoremin { get; set; }
        public string passingscoremax { get; set; }
        public string testingcenter { get; set; }
        public string retakefee { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> isusd { get; set; }
        public string fee { get; set; }
        public string remark { get; set; }
    }
}
