//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public long Id { get; set; }
        public string InvoiceNo { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<long> ProductOrderId { get; set; }
        public Nullable<decimal> TransactionFee { get; set; }
    }
}
