//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public long Id { get; set; }
        public long ProductOrderId { get; set; }
        public int TicketId { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public string PromoCode { get; set; }
        public System.DateTime OrderDate { get; set; }
    }
}
