//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransaction
    {
        public long Id { get; set; }
        public string OrderReferenceNo { get; set; }
        public string TransactionId { get; set; }
        public string PaymentType { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status { get; set; }
        public string ErrorDescription { get; set; }
        public string AuthenticationCode { get; set; }
        public string PaymentGateway { get; set; }
        public string Signature { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string AdditionalInformation { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> TransactionFee { get; set; }
    }
}
