//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class privatebook
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string name { get; set; }
        public string company { get; set; }
        public string position { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> noofpax { get; set; }
        public string preferredvenue { get; set; }
        public System.DateTime preferreddate1 { get; set; }
        public Nullable<System.DateTime> preferreddate2 { get; set; }
        public Nullable<System.DateTime> preferreddate3 { get; set; }
        public string preferredtrainer1 { get; set; }
        public string preferredtrainer2 { get; set; }
        public string preferredtrainer3 { get; set; }
        public Nullable<int> scheme { get; set; }
        public string remarks { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<bool> istimeticker { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public string businessRefNo { get; set; }
        public Nullable<int> dashid { get; set; }
    }
}
