//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrder
    {
        public long Id { get; set; }
        public string ReferenceNo { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> EntityId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime CheckoutDate { get; set; }
        public int Status { get; set; }
        public string ContactName1 { get; set; }
        public string ContactPhone1 { get; set; }
        public string ContactEmail1 { get; set; }
        public string ContactBillingAddress1 { get; set; }
        public string ContactName2 { get; set; }
        public string ContactPhone2 { get; set; }
        public string ContactEmail2 { get; set; }
        public Nullable<decimal> PriceWithGst { get; set; }
        public string ContactCompany1 { get; set; }
    }
}
