//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class quotation
    {
        public int Id { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> NoOfPax { get; set; }
        public string Upload { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string QuotationNo { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Remark { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<bool> isbundle { get; set; }
        public Nullable<bool> isPurchasedExam { get; set; }
        public Nullable<decimal> UnitExamPrice { get; set; }
    }
}
