//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticketdetail
    {
        public int id { get; set; }
        public string guid { get; set; }
        public Nullable<int> dashid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> entityid { get; set; }
        public Nullable<int> tickettype { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string filename { get; set; }
        public int status { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public string email { get; set; }
        public string fullname { get; set; }
        public string phoneno { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<int> classid { get; set; }
        public Nullable<int> bookingtype { get; set; }
        public Nullable<int> ticketid { get; set; }
        public string IcNo { get; set; }
        public string CompanyName { get; set; }
    }
}
