//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainerEvaluation
    {
        public int id { get; set; }
        public Nullable<int> trainerId { get; set; }
        public Nullable<decimal> testimonials { get; set; }
        public Nullable<decimal> evalQuestions { get; set; }
        public Nullable<decimal> competency { get; set; }
        public Nullable<decimal> communication { get; set; }
        public Nullable<decimal> practical { get; set; }
        public Nullable<decimal> engaging { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<System.DateTime> datemodified { get; set; }
    }
}
