//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class userDashboard
    {
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public Nullable<int> type { get; set; }
        public string postitle { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public string creationlocation { get; set; }
        public Nullable<System.DateTime> datemodified { get; set; }
        public string phoneno { get; set; }
        public Nullable<int> status { get; set; }
    }
}
