//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class userlink
    {
        public int id { get; set; }
        public int userid { get; set; }
        public int entityid { get; set; }
        public int usertype { get; set; }
        public Nullable<System.DateTime> activationdate { get; set; }
        public string activationkey { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public int status { get; set; }
    }
}
