//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string guid { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public string title { get; set; }
        public string gender { get; set; }
        public string nric { get; set; }
        public string passport { get; set; }
        public string nationality { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string jobtitle { get; set; }
        public string mobileno { get; set; }
        public string phoneno { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postcode { get; set; }
        public string country { get; set; }
        public string langspoken { get; set; }
        public string langwritten { get; set; }
        public string avatar { get; set; }
        public Nullable<int> ax1 { get; set; }
        public Nullable<int> ax2 { get; set; }
        public Nullable<int> ay1 { get; set; }
        public Nullable<int> ay2 { get; set; }
        public string profilebanner { get; set; }
        public Nullable<int> pfx1 { get; set; }
        public Nullable<int> pfx2 { get; set; }
        public Nullable<int> pfy1 { get; set; }
        public Nullable<int> pfy2 { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public string creationlocation { get; set; }
        public string creationip { get; set; }
        public Nullable<System.DateTime> activationdate { get; set; }
        public string activationkey { get; set; }
        public Nullable<System.DateTime> lastlogintime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<bool> isSBLKhas { get; set; }
        public Nullable<bool> isSMETAP { get; set; }
        public Nullable<bool> isverified { get; set; }
        public string quote { get; set; }
        public string desc { get; set; }
        public Nullable<bool> isTTT { get; set; }
        public string trainerloc { get; set; }
        public string yearsexp { get; set; }
        public string workingexp { get; set; }
        public string industries { get; set; }
        public string clienteles { get; set; }
        public string certification { get; set; }
        public string awards { get; set; }
        public string skills { get; set; }
        public string qualifications { get; set; }
        public string testimonials { get; set; }
        public Nullable<decimal> jokingrate { get; set; }
        public string usernameurl { get; set; }
        public string publication { get; set; }
        public string trainertype { get; set; }
        public string company { get; set; }
        public string software { get; set; }
        public Nullable<double> userrating { get; set; }
        public Nullable<int> ratingtotal { get; set; }
        public Nullable<int> notrained { get; set; }
        public Nullable<int> noclass { get; set; }
        public Nullable<int> rewardsPoint { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingPostCode { get; set; }
        public string ShippingCountry { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingPostCode { get; set; }
        public string BillingCountry { get; set; }
        public string downloads { get; set; }
    }
}
