//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class userCourseEval
    {
        public int id { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<int> classid { get; set; }
        public string remarkstitle { get; set; }
        public string remarksdesc { get; set; }
        public Nullable<System.DateTime> submitdate { get; set; }
        public Nullable<decimal> content_overall { get; set; }
        public Nullable<decimal> content_objectives { get; set; }
        public Nullable<decimal> content_topics { get; set; }
        public Nullable<decimal> content_organized { get; set; }
        public Nullable<decimal> content_dedicated { get; set; }
        public Nullable<decimal> content_summary { get; set; }
        public Nullable<decimal> content_clarity { get; set; }
        public Nullable<decimal> content_relevance { get; set; }
        public Nullable<decimal> overallscore { get; set; }
        public Nullable<int> userid { get; set; }
        public string username { get; set; }
        public string useremail { get; set; }
        public string userphone { get; set; }
        public int status { get; set; }
    }
}
