//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTrainerEval
    {
        public int id { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<int> classid { get; set; }
        public Nullable<int> trainerid { get; set; }
        public string remarkstitle { get; set; }
        public string remarksdesc { get; set; }
        public Nullable<System.DateTime> submitdate { get; set; }
        public Nullable<decimal> trainer_summary { get; set; }
        public Nullable<decimal> trainer_knowledge { get; set; }
        public Nullable<decimal> trainer_ability { get; set; }
        public Nullable<decimal> trainer_competent { get; set; }
        public Nullable<decimal> trainer_communicate { get; set; }
        public Nullable<decimal> trainer_practical { get; set; }
        public Nullable<decimal> trainer_engaging { get; set; }
        public Nullable<decimal> overallscore { get; set; }
        public Nullable<int> userid { get; set; }
        public string username { get; set; }
        public string useremail { get; set; }
        public string userphone { get; set; }
        public int status { get; set; }
    }
}
