//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quorse.EntityFramework.EntityFramework.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class useranalytic
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> usersource { get; set; }
        public Nullable<System.DateTime> stamp { get; set; }
        public Nullable<int> type { get; set; }
        public string IP { get; set; }
    }
}
